### ISSUE TITLE
Importing the library correctly

### ISSUE THREAD

**Issue by steowens** [greiman/SdFat#20]
I am not exactly sure how to import this library into Arduino 1.6.5.  I tried copying the sdfat-master folder to the Libraries directory but that results in a compilation error unable to Locate Sdfat.h  What is the correct way to get this library working in Arduino 1.6.5 and why did the Arduino folks change things in a way that breaks legacy libraries?  (you don't need to answer that last, that is just me engaging in self pity).

**Comment by millerlp** [comment]
Inside the SdFat-master folder that you got from github, you will find a
few other directories, including one labeled simply 'SdFat'. That is the
folder (the entire SdFat folder and its contents) that you need to put in
your Arduino/libraries/ directory.

On Mon, Sep 28, 2015 at 1:06 PM, Steve Owens <notifications@github.com>
wrote:

> I am not exactly sure how to import this library into Arduino 1.6.5. I
> tried copying the sdfat-master folder to the Libraries directory but that
> results in a compilation error unable to Locate Sdfat.h What is the correct
> way to get this library working in Arduino 1.6.5 and why did the Arduino
> folks change things in a way that breaks legacy libraries? (you don't need
> to answer that last, that is just me engaging in self pity).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greiman/SdFat/issues/20>.
>



-- 
___________________________
Luke Miller

**Comment by AlexCalibur** [comment]
With Arduino 1.6.5, libraries can also be include in user space.
In your sketchbook, the is a special folder named 'libraries', copy SdFat dir at this place and restart Arduino IDE.

**Comment by steowens** [comment]
Thanks for the info.

**Comment by greiman** [comment]
Solved
