### PR TITLE
chore(stm32): manage SPI API changes

### LINKED ISSUE #454: STM32duino and SdFat
Hello Greiman,
I used, under IDE Arduino 2.2.1, STM32duino 2.6.0 and SdFat 2.2.2 : perfect, it worked perfectly. 
Since I upgraded from STM32duino 2.6.0 to 2.7.0, it generates errors, here they are:

```
c:\Users\JF\Documents\Arduino\libraries\SdFat\src\SpiDriver\SdSpiSTM32Core.cpp: In member function 'void SdSpiArduinoDriver::send(const uint8_t*, size_t)':
c:\Users\JF\Documents\Arduino\libraries\SdFat\src\SpiDriver\SdSpiSTM32Core.cpp:63:18: error: no matching function for call to 'SPIClass::transfer(uint8_t*, uint8_t [512], size_t&)'
   63 |   m_spi->transfer(const_cast<uint8_t*>(buf), rxBuf, count);
      |   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\Users\JF\Documents\Arduino\libraries\SdFat\src\SpiDriver\SdSpiDriver.h:90,
                 from c:\Users\JF\Documents\Arduino\libraries\SdFat\src\SpiDriver\SdSpiSTM32Core.cpp:26:
C:\Users\JF\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.0\libraries\SPI\src/SPI.h:202:21: note: candidate: 'virtual uint8_t SPIClass::transfer(uint8_t)'
  202 |     virtual uint8_t transfer(uint8_t _data);
      |                     ^~~~~~~~
C:\Users\JF\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.0\libraries\SPI\src/SPI.h:202:21: note:   candidate expects 1 argument, 3 provided
C:\Users\JF\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.0\libraries\SPI\src/SPI.h:204:18: note: candidate: 'virtual void SPIClass::transfer(void*, size_t)'
  204 |     virtual void transfer(void *buf, size_t count);
      |                  ^~~~~~~~
C:\Users\JF\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.0\libraries\SPI\src/SPI.h:204:18: note:   candidate expects 2 arguments, 3 provided

exit status 1

Compilation error: exit status 1
```

Is there a solution by keeping the STM32duino 2.7.0 version ?

### PR DESCRIPTION
**Pull request by fpistm**
Fixes #454.

### CODE REVIEW

**Comment by greiman** [comment]
I will add this to SdFat-beta.  I only update SdFat after changes have been in SdFat-beta for a while.

I also like to collect a number of changes so users pestered by the Arduino IDE every week.

**Comment by fpistm** [comment]
Hi @greiman ,
no worry. up to you, this is mainly to provide a fix to the opened issue.
